global:
  resolve_timeout: 5m
  smtp_from: 'test@example.com'
  smtp_smarthost: 'mail:1025'
  smtp_require_tls: false

route:
  group_by: ['alertname', 'instance']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'mailtest'

receivers:
- name: 'mailtest'
  email_configs:
    - to: 'root@localhost.localdomain'
      send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']
