version: '3'

volumes:
  prometheus_data:
    driver: local

  alertmanager_data:
    driver: local

  grafana_data:
    driver: local

  loki_data:
    driver: local

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    restart: always

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    ports:
      - 9093:9093
    restart: always

  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    restart: always

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    volumes:
      - /:/rootfs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    ports:
      - 9100:9100
    restart: unless-stopped

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
    - 18080:8080
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped

  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      - loki_data:/tmp/loki
    ports:
      - 3100:3100
    restart: always

  promtail:
    image: grafana/promtail
    container_name: promtail
    ports:
      - 9080:9080
    command: -config.file=/etc/promtail/flog-config.yml
    volumes:
      - ./log:/var/log
      - ./promtail/flog-config.yml:/etc/promtail/flog-config.yml
    restart: unless-stopped

  flog-logger:
    image: mingrammer/flog
    container_name: flog_logger
    command: -n 5 -d 5 -t log -w -o /var/log/flog.log -l
    volumes:
      - ./log:/var/log
    restart: unless-stopped

  mail:
    image: schickling/mailcatcher
    container_name: mail
    ports:
      - 1025:1025
      - 1080:1080
    restart: unless-stopped

