global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

rule_files:
  - alert_rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - alertmanager:9093

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
        - node-exporter:9100

  - job_name: 'service'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://alertmanager:9093
        - http://grafana:3000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'container'
    static_configs:
      - targets:
        - cadvisor:8080
